server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockwise?createDatabaseIfNotExist=true
    username: yassine
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

seed:
  enabled: false

rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem